# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  ELIXIR_VERSION: 1.15.2
  OTP_VERSION: 26.0.2
  ALPINE_VERSION: 3.18.2

stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

.elixir: &elixir
  image: 'hexpm/elixir:$ELIXIR_VERSION-erlang-$OTP_VERSION-alpine-$ALPINE_VERSION'
  before_script:
    - apk add git
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV

lint:elixir:
  extends: .elixir
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted

test:elixir:
  extends: .elixir
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix test --no-start
