apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redpanda
  name: redpanda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
